[package]
name = "neuro-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"

[[bin]]
name = "hh_sim"
path = "src/bin/hudgkin_huxley.rs"

[features]
print = []
